# Generated by Django 4.2.10 on 2024-03-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_staff_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_Notifications',
            new_name='Staff_Notification',
        ),
    ]
