# Generated by Django 4.2.10 on 2024-03-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_staff_notifications_staff_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
